ifeq ($(BOARD_HAVE_BROADCOM_GPS), true)

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := glgps
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := glgps 
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gps.imx5x.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/hw
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES := gps.imx5x.so
include $(BUILD_PREBUILT)

endif # BOARD_HAVE_BROADCOM_GPS
